@echo off
echo [1/3] Building WASM...
wasm-pack build --target web
echo [2/3] Inlining WASM bytes...
node inline-wasm.js
echo [3/3] Copying pkg to webos-dist...
xcopy /E /Y pkg\* webos-dist\pkg\
echo Done.
